In [1]:
'''
Problem Statement : Restaurant owner claims that 50% customers are male and 50% are female. we need to validate his claim.
We need to validate this claim with significance level of 0.05


H1 : proportion != 0.5

H0 : proportion = 0.5

'''

'\nProblem Statement : Restaurant owner claims that 50% customers are male and 50% are female. we need to validate his claim.\nWe need to validate this claim with significance level of 0.05\n\n\nH1 : proportion != 0.5\n\nH0 : proportion = 0.5\n\n'

In [2]:
from seaborn import load_dataset
tips = load_dataset('tips')
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
sample_size = 50
sample = tips.sample(n=sample_size)
sample

     total_bill   tip     sex smoker   day    time  size
195        7.56  1.44    Male     No  Thur   Lunch     2
40        16.04  2.24    Male     No   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
74        14.73  2.20  Female     No   Sat  Dinner     2
184       40.55  3.00    Male    Yes   Sun  Dinner     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
10        10.27  1.71    Male     No   Sun  Dinner     2
25        17.81  2.34    Male     No   Sat  Dinner     4
91        22.49  3.50    Male     No   Fri  Dinner     2
9         14.78  3.23    Male     No   Sun  Dinner     2
136       10.33  2.00  Female     No  Thur   Lunch     2
66        16.45  2.47  Female     No   Sat  Dinner     2
138       16.00  2.00    Male    Yes  Thur   Lunch     2
124       12.48  2.52  Female     No  Thur   Lunch     2
147       11.87  1.63  Female     No  Thur   Lunch     2
160       21.50  3.50    Male     No   Sun  Dinner     4
141       34.30  6.70    Male     No  Thur   Lunch     6
64        17.59  2.64    Male     No   Sat  Dinner     3
139       13.16  2.75  Female     No  Thur   Lunch     2
232       11.61  3.39    Male     No   Sat  Dinner     2
17        16.29  3.71    Male     No   Sun  Dinner     3
193       15.48  2.02    Male    Yes  Thur   Lunch     2
42        13.94  3.06    Male     No   Sun  Dinner     2
132       11.17  1.50  Female     No  Thur   Lunch     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2
71        17.07  3.00  Female     No   Sat  Dinner     3
234       15.53  3.00    Male    Yes   Sat  Dinner     2
119       24.08  2.92  Female     No  Thur   Lunch     4
179       34.63  3.55    Male    Yes   Sun  Dinner     2
126        8.52  1.48    Male     No  Thur   Lunch     2
93        16.32  4.30  Female    Yes   Fri  Dinner     2
231       15.69  3.00    Male    Yes   Sat  Dinner     3
89        21.16  3.00    Male     No  Thur   Lunch     2
213       13.27  2.50  Female    Yes   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
223       15.98  3.00  Female     No   Fri   Lunch     3
14        14.83  3.02  Female     No   Sun  Dinner     2
56        38.01  3.00    Male    Yes   Sat  Dinner     4
58        11.24  1.76    Male    Yes   Sat  Dinner     2
99        12.46  1.50    Male     No   Fri  Dinner     2
73        25.28  5.00  Female    Yes   Sat  Dinner     2
216       28.15  3.00    Male    Yes   Sat  Dinner     5
12        15.42  1.57    Male     No   Sun  Dinner     2
39        31.27  5.00    Male     No   Sat  Dinner     3
198       13.00  2.00  Female    Yes  Thur   Lunch     2
104       20.92  4.08  Female     No   Sat  Dinner     2
188       18.15  3.50  Female    Yes   Sun  Dinner     3
27        12.69  2.00    Male     No   Sat  Dinner     2
13        18.43  3.00    Male     No   Sun  Dinner     4

In [6]:
observed_frequencies = sample['sex'].value_counts().values.tolist()
observed_frequencies
# from sample

[30, 20]

In [7]:
expected_frequencies = [sample_size*0.5, sample_size*0.5]
expected_frequencies
# claimed

[25.0, 25.0]

In [8]:
from scipy import stats
chi_sq_stat,p_value = stats.chisquare(f_obs = observed_frequencies, f_exp = expected_frequencies)

In [9]:
chi_sq_stat,p_value

(np.float64(2.0), np.float64(0.15729920705028105))

In [10]:
alpha = 0.05
d_freedom = len(observed_frequencies)-1 #Degrees of Freedom
chi_square_critical = stats.chi2.ppf(1-alpha,d_freedom)
chi_square_critical

np.float64(3.841458820694124)

In [11]:
if chi_sq_stat > chi_square_critical:
  print('Decision : Reject the H0')
else:
  print("Decision : Failed to reject the H0")

Decision : Failed to reject the H0

In [10]:
'''
As we have failed to reject the H0 (in simple we can say we need to accept H0)
ie the claim made by owner that 50% customer are male and 50% are female is statisticaly significant
'''

'\nAs we have failed to reject the H0 (in simple we can say we need to accept H0)\nie the claim made by owner that 50% customer are male and 50% are female is statisticaly significant\n'

## Kolmogorov-Smirnov Test
- Purpose : Test if the sample matches a given distribution
- When to use : Use for continous data to check goodness of fit for given continuous distribution
- The sample should be random and claimed distribution should be continuous


Example Claim : The tips['total_bill'] follows normal distribution.

In [11]:
'''
Null Hypothesis H0 : the sample follows normal distribution
Alternate Hypothesis H1 : sample doesn't follow normal distribution

significance level = 0.05
'''

"\nNull Hypothesis H0 : the sample follows normal distribution\nAlternate Hypothesis H1 : sample doesn't follow normal distribution\n\nsignificance level = 0.05\n"

In [12]:
alpha =0.05
sample = tips['total_bill']
ks_stat,p_value = stats.kstest(sample,'norm',args = (sample.mean(),sample.std()))

print(f"KS Stat={ks_stat}, p_value={p_value}")

KS Stat=0.11875388157506361, p_value=0.001866364156047776

In [13]:
def decision(p_value,alpha):
  if p_value<alpha:
    print("Decision : Reject H0")
  else:
    print("Decision : Failed to reject the H0")

In [14]:
decision(p_value,alpha)
# The data doesn't follow normal distribution

Decision : Reject H0

## One Sample t-test
- Purpose : Check if the claimed population mean is same as that of sample mean using a single sample
- When to use : Used for continous data, and comparing sample mean to a specific population mean
- Assumptions : Sample should be random, data follows normal distribution


Example claim : The average of 'tip' is 2.

In [15]:
'''
H0 : The average tip is 2
H1 : The average tip is not 2
'''

'\nH0 : The average tip is 2\nH1 : The average tip is not 2\n'

In [16]:
sample = tips['tip']
sample

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ...
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [17]:
t_stat,p_value = stats.ttest_1samp(sample,2)

print(f"{t_stat=}, {p_value=}")

t_stat=np.float64(11.270006661412024), p_value=np.float64(5.627791279430061e-24)

In [18]:
decision(p_value,alpha)

Decision : Reject H0

## Pearson Correlation Test
- Purpose : Tests whether two continuous data have linear relationship or not
- When to use : Used for continous data to test linear relationship
- Assumptions: Data should be continous, normaly distributed

Example claim : 'total_bill' and 'tip' have linear relationship

In [19]:
'''
H0 : The relationship is not linear

H1 : The relationship is linear
'''

'\nH0 : The relationship is not linear\n\nH1 : The relationship is linear\n'

In [20]:
stat,p_value = stats.pearsonr(tips['total_bill'],tips['tip'])

print(f"{stat=} , {p_value=}")

stat=np.float64(0.6757341092113645) , p_value=np.float64(6.692470646863714e-34)

In [21]:
decision(p_value,alpha)
# As we reject H0, the relationship is significantly linear

Decision : Reject H0

In [22]:
tips[['total_bill','tip']].corr()

            total_bill       tip
total_bill    1.000000  0.675734
tip           0.675734  1.000000

## Two Sample t-test (Test of independence)

- Purpose : Compare means of two sample
- Use : Use for categorical and continous variable

Example Claim : The average of tip from Male and Female customers is same

In [23]:
'''
H0 : The average tip from Male and Female customers are different
H1 : The average tip from Male and Female customers are same
'''

'\nH0 : The average tip from Male and Female customers are different\nH1 : The average tip from Male and Female customers are same\n'

In [24]:
sample_male = tips[tips['sex']=='Male']['tip']
sample_female = tips[tips['sex']=='Female']['tip']

stat,p_value = stats.ttest_ind(sample_male,sample_female)

print(f"{stat=} , {p_value=}")

stat=np.float64(1.387859705421269) , p_value=np.float64(0.16645623503456755)

In [25]:
decision(p_value,alpha)

# The average tip from Male and Female customers are different

Decision : Failed to reject the H0

In [26]:
alpha

0.05

## One - way ANOVA
- Purpose : Compares means of three or more sample
- Use : Used for categorical data vs numerical data with >2 groups

Example Claim : Average of total_bill differs by day of the week.

In [27]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [28]:
'''
H0 : The average is same for all days of week
H1 : The average differs for days of week
'''

'\nH0 : The average is same for all days of week\nH1 : The average differs for days of week\n'

In [29]:
days = tips['day'].unique()
days

groups = [tips[tips['day']==day]['total_bill'] for day in days]

In [30]:
stat,p_value = stats.f_oneway(*groups)
print(f"{stat=} , {p_value=}")

stat=np.float64(2.7674794432863363) , p_value=np.float64(0.04245383328951916)

In [31]:
decision(p_value,alpha)

# as we reject H0, the average differs significantly for days of the week

Decision : Reject H0

## Spearman Correlation Test
- Purpose : Test linear or non-linear relationships between variables
- Use : Used for continuous data

Example Claim : total bill and tips have a strong relationship

In [32]:
'''
H0 : There is no relationship
H1 : There is a strong relationship
'''

'\nH0 : There is no relationship\nH1 : There is a strong relationship\n'

In [33]:
stat,p_value = stats.spearmanr(tips['total_bill'],tips['tip'])

print(f"{stat=} , {p_value=}")

stat=np.float64(0.6789681219001009) , p_value=np.float64(2.501158440923619e-34)

In [34]:
decision(p_value,alpha)

## there is a strong relationship between total_bill and tip

Decision : Reject H0

## Kruskal-Wallis Test
- Purpose : Compare means of three or more groups
- Use : Used for categorical and numerical data when numerical data is not normaly distributed

Example claim : Average of total_bill differs for week days

In [35]:
'''
H0 : Averages are same
H1 : Averages are different
'''

'\nH0 : Averages are same\nH1 : Averages are different\n'

In [36]:
stat,p_value = stats.kruskal(*groups)

print(f"{stat=} , {p_value=}")

stat=np.float64(10.403076391436972) , p_value=np.float64(0.015433008201042065)

In [37]:
decision(p_value,alpha)

Decision : Reject H0