In [ ]:
import pandas as pd,numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/INM/ML_Feb26/vitamin_deficiency_disease_dataset_20260123.csv')
df

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,has_night_blindness,has_fatigue,has_bleeding_gums,has_bone_pain,has_muscle_weakness,has_numbness_tingling,has_memory_problems,has_pale_skin,disease_diagnosis,has_multiple_deficiencies
0,79,Male,24.8,Former,NaN,Active,Vegetarian,High,High,Mid,...,0,0,0,0,0,0,0,0,Healthy,0
1,77,Female,39.9,Former,Moderate,Light,Omnivore,Low,Low,Low,...,0,0,0,1,0,0,0,0,Rickets_Osteomalacia,0
2,24,Male,26.4,Former,Heavy,Moderate,Omnivore,Low,High,High,...,1,0,0,0,0,0,0,0,Healthy,0
3,69,Male,23.1,Never,Heavy,Moderate,Vegetarian,High,Low,Low,...,0,0,0,0,0,1,1,0,Anemia,0
4,63,Male,29.6,Never,NaN,Moderate,Vegetarian,Moderate,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,25,Female,21.6,Former,Heavy,Active,Pescatarian,Moderate,Middle,High,...,1,0,0,0,0,0,0,0,Healthy,0
3996,50,Male,29.5,Former,Moderate,Sedentary,Vegetarian,Low,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0
3997,34,Female,24.8,Never,NaN,Active,Pescatarian,Moderate,Low,Low,...,0,1,0,0,0,1,1,0,Anemia,0
3998,39,Female,26.9,Former,Heavy,Active,Omnivore,High,Low,High,...,1,0,0,0,0,0,0,0,Anemia,0
3999,41,Female,28.0,Current,NaN,Sedentary,Omnivore,High,High,High,...,0,0,0,0,0,0,1,0,Anemia,0

In [ ]:
df.columns

Index(['age', 'gender', 'bmi', 'smoking_status', 'alcohol_consumption',
       'exercise_level', 'diet_type', 'sun_exposure', 'income_level',
       'latitude_region', 'vitamin_a_percent_rda', 'vitamin_c_percent_rda',
       'vitamin_d_percent_rda', 'vitamin_e_percent_rda',
       'vitamin_b12_percent_rda', 'folate_percent_rda', 'calcium_percent_rda',
       'iron_percent_rda', 'hemoglobin_g_dl', 'serum_vitamin_d_ng_ml',
       'serum_vitamin_b12_pg_ml', 'serum_folate_ng_ml', 'symptoms_count',
       'symptoms_list', 'has_night_blindness', 'has_fatigue',
       'has_bleeding_gums', 'has_bone_pain', 'has_muscle_weakness',
       'has_numbness_tingling', 'has_memory_problems', 'has_pale_skin',
       'disease_diagnosis', 'has_multiple_deficiencies'],
      dtype='object')

In [ ]:
df['disease_diagnosis'].value_counts()
# We can train a model to predict the disease with given vitamin levels, health indicators and symptoms

disease_diagnosis
Healthy                 1509
Anemia                  1245
Rickets_Osteomalacia    1029
Night_Blindness          122
Scurvy                    95
Name: count, dtype: int64

In [ ]:
df['has_multiple_deficiencies'].value_counts()

# We can train a model to predict the vitamin deficieny presence with given vitamin levels, health indicators and symptoms

has_multiple_deficiencies
0    2611
1    1389
Name: count, dtype: int64

In [ ]:
data = df.copy()

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 34 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        4000 non-null   int64
 1   gender                     4000 non-null   object
 2   bmi                        4000 non-null   float64
 3   smoking_status             4000 non-null   object
 4   alcohol_consumption        2722 non-null   object
 5   exercise_level             4000 non-null   object
 6   diet_type                  4000 non-null   object
 7   sun_exposure               4000 non-null   object
 8   income_level               4000 non-null   object
 9   latitude_region            4000 non-null   object
 10  vitamin_a_percent_rda      4000 non-null   float64
 11  vitamin_c_percent_rda      4000 non-null   float64
 12  vitamin_d_percent_rda      4000 non-null   float64
 13  vitamin_e_percent_rda      4000 non-null   float64
 14  vitamin_b12_percent_rda    4000 non-null   float64
 15  folate_percent_rda         4000 non-null   float64
 16  calcium_percent_rda        4000 non-null   float64
 17  iron_percent_rda           4000 non-null   float64
 18  hemoglobin_g_dl            4000 non-null   float64
 19  serum_vitamin_d_ng_ml      4000 non-null   float64
 20  serum_vitamin_b12_pg_ml    4000 non-null   float64
 21  serum_folate_ng_ml         4000 non-null   float64
 22  symptoms_count             4000 non-null   int64
 23  symptoms_list              2672 non-null   object
 24  has_night_blindness        4000 non-null   int64
 25  has_fatigue                4000 non-null   int64
 26  has_bleeding_gums          4000 non-null   int64
 27  has_bone_pain              4000 non-null   int64
 28  has_muscle_weakness        4000 non-null   int64
 29  has_numbness_tingling      4000 non-null   int64
 30  has_memory_problems        4000 non-null   int64
 31  has_pale_skin              4000 non-null   int64
 32  disease_diagnosis          4000 non-null   object
 33  has_multiple_deficiencies  4000 non-null   int64
dtypes: float64(13), int64(11), object(10)
memory usage: 1.0+ MB

In [ ]:
data.isna().sum()

age                             0
gender                          0
bmi                             0
smoking_status                  0
alcohol_consumption          1278
exercise_level                  0
diet_type                       0
sun_exposure                    0
income_level                    0
latitude_region                 0
vitamin_a_percent_rda           0
vitamin_c_percent_rda           0
vitamin_d_percent_rda           0
vitamin_e_percent_rda           0
vitamin_b12_percent_rda         0
folate_percent_rda              0
calcium_percent_rda             0
iron_percent_rda                0
hemoglobin_g_dl                 0
serum_vitamin_d_ng_ml           0
serum_vitamin_b12_pg_ml         0
serum_folate_ng_ml              0
symptoms_count                  0
symptoms_list                1328
has_night_blindness             0
has_fatigue                     0
has_bleeding_gums               0
has_bone_pain                   0
has_muscle_weakness             0
has_numbness_tingling           0
has_memory_problems             0
has_pale_skin                   0
disease_diagnosis               0
has_multiple_deficiencies       0
dtype: int64

In [ ]:
data['alcohol_consumption'].value_counts()

alcohol_consumption
Moderate    1372
Heavy       1350
Name: count, dtype: int64

In [ ]:
data[data['alcohol_consumption'].isna()]

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,has_night_blindness,has_fatigue,has_bleeding_gums,has_bone_pain,has_muscle_weakness,has_numbness_tingling,has_memory_problems,has_pale_skin,disease_diagnosis,has_multiple_deficiencies
0,79,Male,24.8,Former,NaN,Active,Vegetarian,High,High,Mid,...,0,0,0,0,0,0,0,0,Healthy,0
4,63,Male,29.6,Never,NaN,Moderate,Vegetarian,Moderate,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0
13,46,Male,28.0,Former,NaN,Active,Pescatarian,High,High,Mid,...,0,0,0,0,0,0,0,0,Healthy,0
14,45,Male,26.7,Former,NaN,Active,Pescatarian,High,High,Mid,...,0,0,0,0,0,0,0,0,Healthy,0
16,49,Female,23.9,Current,NaN,Active,Omnivore,High,Low,Low,...,0,0,0,0,0,0,0,0,Healthy,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3982,29,Female,26.7,Never,NaN,Sedentary,Omnivore,Low,Low,High,...,0,1,0,0,0,0,0,0,Rickets_Osteomalacia,1
3985,62,Female,29.8,Former,NaN,Moderate,Pescatarian,High,Low,High,...,1,0,0,0,0,0,0,0,Healthy,0
3993,57,Female,28.1,Former,NaN,Sedentary,Omnivore,High,High,Mid,...,0,0,0,0,0,0,0,0,Healthy,0
3997,34,Female,24.8,Never,NaN,Active,Pescatarian,Moderate,Low,Low,...,0,1,0,0,0,1,1,0,Anemia,0
3999,41,Female,28.0,Current,NaN,Sedentary,Omnivore,High,High,High,...,0,0,0,0,0,0,1,0,Anemia,0

In [ ]:
## assumption -> null values for alcohol_consumption means low-none consumption

data['alcohol_consumption'].fillna('Low-None',inplace=True)

/tmp/ipykernel_6045/1618674790.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['alcohol_consumption'].fillna('Low-None',inplace=True)

In [ ]:
data

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,has_night_blindness,has_fatigue,has_bleeding_gums,has_bone_pain,has_muscle_weakness,has_numbness_tingling,has_memory_problems,has_pale_skin,disease_diagnosis,has_multiple_deficiencies
0,79,Male,24.8,Former,Low-None,Active,Vegetarian,High,High,Mid,...,0,0,0,0,0,0,0,0,Healthy,0
1,77,Female,39.9,Former,Moderate,Light,Omnivore,Low,Low,Low,...,0,0,0,1,0,0,0,0,Rickets_Osteomalacia,0
2,24,Male,26.4,Former,Heavy,Moderate,Omnivore,Low,High,High,...,1,0,0,0,0,0,0,0,Healthy,0
3,69,Male,23.1,Never,Heavy,Moderate,Vegetarian,High,Low,Low,...,0,0,0,0,0,1,1,0,Anemia,0
4,63,Male,29.6,Never,Low-None,Moderate,Vegetarian,Moderate,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,25,Female,21.6,Former,Heavy,Active,Pescatarian,Moderate,Middle,High,...,1,0,0,0,0,0,0,0,Healthy,0
3996,50,Male,29.5,Former,Moderate,Sedentary,Vegetarian,Low,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0
3997,34,Female,24.8,Never,Low-None,Active,Pescatarian,Moderate,Low,Low,...,0,1,0,0,0,1,1,0,Anemia,0
3998,39,Female,26.9,Former,Heavy,Active,Omnivore,High,Low,High,...,1,0,0,0,0,0,0,0,Anemia,0
3999,41,Female,28.0,Current,Low-None,Sedentary,Omnivore,High,High,High,...,0,0,0,0,0,0,1,0,Anemia,0

In [ ]:
data['symptoms_list']
## the symptoms in this list are already handled using one-hot encoding -> each symptom has a column associated to it

## We can drop this column

0                                             NaN
1                                       bone_pain
2                        dry_skin;night_blindness
3               numbness_tingling;memory_problems
4                                             NaN
                          ...
3995                              night_blindness
3996                                          NaN
3997    numbness_tingling;memory_problems;fatigue
3998                     dry_skin;night_blindness
3999                              memory_problems
Name: symptoms_list, Length: 4000, dtype: object

In [ ]:
data.drop('symptoms_list',axis=1,inplace=True)
data

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,has_night_blindness,has_fatigue,has_bleeding_gums,has_bone_pain,has_muscle_weakness,has_numbness_tingling,has_memory_problems,has_pale_skin,disease_diagnosis,has_multiple_deficiencies
0,79,Male,24.8,Former,Low-None,Active,Vegetarian,High,High,Mid,...,0,0,0,0,0,0,0,0,Healthy,0
1,77,Female,39.9,Former,Moderate,Light,Omnivore,Low,Low,Low,...,0,0,0,1,0,0,0,0,Rickets_Osteomalacia,0
2,24,Male,26.4,Former,Heavy,Moderate,Omnivore,Low,High,High,...,1,0,0,0,0,0,0,0,Healthy,0
3,69,Male,23.1,Never,Heavy,Moderate,Vegetarian,High,Low,Low,...,0,0,0,0,0,1,1,0,Anemia,0
4,63,Male,29.6,Never,Low-None,Moderate,Vegetarian,Moderate,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,25,Female,21.6,Former,Heavy,Active,Pescatarian,Moderate,Middle,High,...,1,0,0,0,0,0,0,0,Healthy,0
3996,50,Male,29.5,Former,Moderate,Sedentary,Vegetarian,Low,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0
3997,34,Female,24.8,Never,Low-None,Active,Pescatarian,Moderate,Low,Low,...,0,1,0,0,0,1,1,0,Anemia,0
3998,39,Female,26.9,Former,Heavy,Active,Omnivore,High,Low,High,...,1,0,0,0,0,0,0,0,Anemia,0
3999,41,Female,28.0,Current,Low-None,Sedentary,Omnivore,High,High,High,...,0,0,0,0,0,0,1,0,Anemia,0

In [ ]:
data.isna().sum()

age                          0
gender                       0
bmi                          0
smoking_status               0
alcohol_consumption          0
exercise_level               0
diet_type                    0
sun_exposure                 0
income_level                 0
latitude_region              0
vitamin_a_percent_rda        0
vitamin_c_percent_rda        0
vitamin_d_percent_rda        0
vitamin_e_percent_rda        0
vitamin_b12_percent_rda      0
folate_percent_rda           0
calcium_percent_rda          0
iron_percent_rda             0
hemoglobin_g_dl              0
serum_vitamin_d_ng_ml        0
serum_vitamin_b12_pg_ml      0
serum_folate_ng_ml           0
symptoms_count               0
has_night_blindness          0
has_fatigue                  0
has_bleeding_gums            0
has_bone_pain                0
has_muscle_weakness          0
has_numbness_tingling        0
has_memory_problems          0
has_pale_skin                0
disease_diagnosis            0
has_multiple_deficiencies    0
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 33 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        4000 non-null   int64
 1   gender                     4000 non-null   object
 2   bmi                        4000 non-null   float64
 3   smoking_status             4000 non-null   object
 4   alcohol_consumption        4000 non-null   object
 5   exercise_level             4000 non-null   object
 6   diet_type                  4000 non-null   object
 7   sun_exposure               4000 non-null   object
 8   income_level               4000 non-null   object
 9   latitude_region            4000 non-null   object
 10  vitamin_a_percent_rda      4000 non-null   float64
 11  vitamin_c_percent_rda      4000 non-null   float64
 12  vitamin_d_percent_rda      4000 non-null   float64
 13  vitamin_e_percent_rda      4000 non-null   float64
 14  vitamin_b12_percent_rda    4000 non-null   float64
 15  folate_percent_rda         4000 non-null   float64
 16  calcium_percent_rda        4000 non-null   float64
 17  iron_percent_rda           4000 non-null   float64
 18  hemoglobin_g_dl            4000 non-null   float64
 19  serum_vitamin_d_ng_ml      4000 non-null   float64
 20  serum_vitamin_b12_pg_ml    4000 non-null   float64
 21  serum_folate_ng_ml         4000 non-null   float64
 22  symptoms_count             4000 non-null   int64
 23  has_night_blindness        4000 non-null   int64
 24  has_fatigue                4000 non-null   int64
 25  has_bleeding_gums          4000 non-null   int64
 26  has_bone_pain              4000 non-null   int64
 27  has_muscle_weakness        4000 non-null   int64
 28  has_numbness_tingling      4000 non-null   int64
 29  has_memory_problems        4000 non-null   int64
 30  has_pale_skin              4000 non-null   int64
 31  disease_diagnosis          4000 non-null   object
 32  has_multiple_deficiencies  4000 non-null   int64
dtypes: float64(13), int64(11), object(9)
memory usage: 1.0+ MB

In [ ]:
data['gender'].value_counts()

gender
Male      2029
Female    1971
Name: count, dtype: int64

In [ ]:
data['gender'] = data['gender'].apply(lambda x:1 if x=='Male' else 0)
data

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,has_night_blindness,has_fatigue,has_bleeding_gums,has_bone_pain,has_muscle_weakness,has_numbness_tingling,has_memory_problems,has_pale_skin,disease_diagnosis,has_multiple_deficiencies
0,79,1,24.8,Former,Low-None,Active,Vegetarian,High,High,Mid,...,0,0,0,0,0,0,0,0,Healthy,0
1,77,0,39.9,Former,Moderate,Light,Omnivore,Low,Low,Low,...,0,0,0,1,0,0,0,0,Rickets_Osteomalacia,0
2,24,1,26.4,Former,Heavy,Moderate,Omnivore,Low,High,High,...,1,0,0,0,0,0,0,0,Healthy,0
3,69,1,23.1,Never,Heavy,Moderate,Vegetarian,High,Low,Low,...,0,0,0,0,0,1,1,0,Anemia,0
4,63,1,29.6,Never,Low-None,Moderate,Vegetarian,Moderate,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,25,0,21.6,Former,Heavy,Active,Pescatarian,Moderate,Middle,High,...,1,0,0,0,0,0,0,0,Healthy,0
3996,50,1,29.5,Former,Moderate,Sedentary,Vegetarian,Low,High,Low,...,0,0,0,0,0,0,0,0,Healthy,0
3997,34,0,24.8,Never,Low-None,Active,Pescatarian,Moderate,Low,Low,...,0,1,0,0,0,1,1,0,Anemia,0
3998,39,0,26.9,Former,Heavy,Active,Omnivore,High,Low,High,...,1,0,0,0,0,0,0,0,Anemia,0
3999,41,0,28.0,Current,Low-None,Sedentary,Omnivore,High,High,High,...,0,0,0,0,0,0,1,0,Anemia,0

In [ ]:
data['latitude_region'].unique()

array(['Mid', 'Low', 'High'], dtype=object)

In [ ]:
smoking_status_encoder = {'Never':0,'Former':1,'Current':2}
alcohol_consumption_encoder = {'Low-None':0,'Moderate':1,'Heavy':2}
exercise_level_encoder = {'Active':3, 'Light':1, 'Moderate':2, 'Sedentary':0}
diet_type_encoder= {'Vegetarian':0, 'Omnivore':1, 'Pescatarian':2, 'Vegan':3}
sun_exposure_encoder = {'High':2, 'Low':0, 'Moderate':1}
income_level_encoder = {'High':2, 'Low':0, 'Middle':1}
latitude_region_encoder = {'High':2, 'Low':0, 'Mid':1}

disease_encoder = {'Healthy':0, 'Rickets_Osteomalacia':1, 'Anemia':2, 'Night_Blindness':3,
       'Scurvy':4}

In [ ]:
data['smoking_status'] = data['smoking_status'].apply(lambda x:smoking_status_encoder[x])
data['alcohol_consumption'] = data['alcohol_consumption'].apply(lambda x:alcohol_consumption_encoder[x])
data['exercise_level'] = data['exercise_level'].apply(lambda x:exercise_level_encoder[x])
data['diet_type'] = data['diet_type'].apply(lambda x:diet_type_encoder[x])
data['sun_exposure'] = data['sun_exposure'].apply(lambda x:sun_exposure_encoder[x])
data['income_level'] = data['income_level'].apply(lambda x:income_level_encoder[x])
data['latitude_region'] = data['latitude_region'].apply(lambda x:latitude_region_encoder[x])

data['disease_diagnosis'] = data['disease_diagnosis'].apply(lambda x:disease_encoder[x])


data

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,has_night_blindness,has_fatigue,has_bleeding_gums,has_bone_pain,has_muscle_weakness,has_numbness_tingling,has_memory_problems,has_pale_skin,disease_diagnosis,has_multiple_deficiencies
0,79,1,24.8,1,0,3,0,2,2,1,...,0,0,0,0,0,0,0,0,0,0
1,77,0,39.9,1,1,1,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
2,24,1,26.4,1,2,2,1,0,2,2,...,1,0,0,0,0,0,0,0,0,0
3,69,1,23.1,0,2,2,0,2,0,0,...,0,0,0,0,0,1,1,0,2,0
4,63,1,29.6,0,0,2,0,1,2,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,25,0,21.6,1,2,3,2,1,1,2,...,1,0,0,0,0,0,0,0,0,0
3996,50,1,29.5,1,1,0,0,0,2,0,...,0,0,0,0,0,0,0,0,0,0
3997,34,0,24.8,0,0,3,2,1,0,0,...,0,1,0,0,0,1,1,0,2,0
3998,39,0,26.9,1,2,3,1,2,0,2,...,1,0,0,0,0,0,0,0,2,0
3999,41,0,28.0,2,0,0,1,2,2,2,...,0,0,0,0,0,0,1,0,2,0

In [ ]:
data.columns

Index(['age', 'gender', 'bmi', 'smoking_status', 'alcohol_consumption',
       'exercise_level', 'diet_type', 'sun_exposure', 'income_level',
       'latitude_region', 'vitamin_a_percent_rda', 'vitamin_c_percent_rda',
       'vitamin_d_percent_rda', 'vitamin_e_percent_rda',
       'vitamin_b12_percent_rda', 'folate_percent_rda', 'calcium_percent_rda',
       'iron_percent_rda', 'hemoglobin_g_dl', 'serum_vitamin_d_ng_ml',
       'serum_vitamin_b12_pg_ml', 'serum_folate_ng_ml', 'symptoms_count',
       'has_night_blindness', 'has_fatigue', 'has_bleeding_gums',
       'has_bone_pain', 'has_muscle_weakness', 'has_numbness_tingling',
       'has_memory_problems', 'has_pale_skin', 'disease_diagnosis',
       'has_multiple_deficiencies'],
      dtype='object')

In [ ]:
## train test split
from sklearn.model_selection import train_test_split

train_df,test_df = train_test_split(data,test_size=0.2)

features = ['age', 'gender', 'bmi', 'smoking_status', 'alcohol_consumption',
       'exercise_level', 'diet_type', 'sun_exposure', 'income_level',
       'latitude_region', 'vitamin_a_percent_rda', 'vitamin_c_percent_rda',
       'vitamin_d_percent_rda', 'vitamin_e_percent_rda',
       'vitamin_b12_percent_rda', 'folate_percent_rda', 'calcium_percent_rda',
       'iron_percent_rda', 'hemoglobin_g_dl', 'serum_vitamin_d_ng_ml',
       'serum_vitamin_b12_pg_ml', 'serum_folate_ng_ml', 'symptoms_count',
       'has_night_blindness', 'has_fatigue', 'has_bleeding_gums',
       'has_bone_pain', 'has_muscle_weakness', 'has_numbness_tingling',
       'has_memory_problems', 'has_pale_skin']

x_train = train_df[features]
y_train = train_df['disease_diagnosis']

x_test = test_df[features]
y_test = test_df['disease_diagnosis']

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
dt_model = DecisionTreeClassifier(max_depth=3)

In [ ]:
adaboost_model = AdaBoostClassifier(estimator = dt_model , n_estimators=10)

In [ ]:
adaboost_model.fit(x_train,y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=3),
                   n_estimators=10)

In [ ]:
adaboost_model.estimators_

[DecisionTreeClassifier(max_depth=3, random_state=452444847),
 DecisionTreeClassifier(max_depth=3, random_state=1883795817),
 DecisionTreeClassifier(max_depth=3, random_state=1414487326),
 DecisionTreeClassifier(max_depth=3, random_state=1036039377),
 DecisionTreeClassifier(max_depth=3, random_state=521398257),
 DecisionTreeClassifier(max_depth=3, random_state=1920057689),
 DecisionTreeClassifier(max_depth=3, random_state=707535772),
 DecisionTreeClassifier(max_depth=3, random_state=1039741598),
 DecisionTreeClassifier(max_depth=3, random_state=1773034742),
 DecisionTreeClassifier(max_depth=3, random_state=528181740)]

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
y_pred = adaboost_model.predict(x_train)
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1202
           1       1.00      1.00      1.00       841
           2       0.99      1.00      0.99       978
           3       1.00      0.94      0.97       103
           4       1.00      0.92      0.96        76

    accuracy                           0.99      3200
   macro avg       1.00      0.97      0.98      3200
weighted avg       0.99      0.99      0.99      3200

In [ ]:
y_pred = adaboost_model.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       307
           1       1.00      1.00      1.00       188
           2       0.99      1.00      0.99       267
           3       1.00      1.00      1.00        19
           4       1.00      0.95      0.97        19

    accuracy                           1.00       800
   macro avg       1.00      0.99      0.99       800
weighted avg       1.00      1.00      1.00       800

## GBM Classifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier

In [ ]:
gbc = GradientBoostingClassifier(
    n_estimators=4,
    max_depth=3,
    learning_rate=0.1
)

In [ ]:
gbc.fit(x_train,y_train)

GradientBoostingClassifier(n_estimators=4)

In [ ]:
y_pred = gbc.predict(x_train)
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97      1202
           1       1.00      0.98      0.99       841
           2       0.98      0.97      0.97       978
           3       1.00      0.90      0.95       103
           4       1.00      1.00      1.00        76

    accuracy                           0.98      3200
   macro avg       0.99      0.97      0.98      3200
weighted avg       0.98      0.98      0.98      3200

In [ ]:
y_pred = adaboost_model.predict(x_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       307
           1       1.00      1.00      1.00       188
           2       0.99      1.00      0.99       267
           3       1.00      1.00      1.00        19
           4       1.00      0.95      0.97        19

    accuracy                           1.00       800
   macro avg       1.00      0.99      0.99       800
weighted avg       1.00      1.00      1.00       800

## XGBoost Classifier

In [ ]:
#pip install xgboost

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb_clf = XGBClassifier(
    n_estimators=6,
    max_depth=6,
    max_features=4,
    learning_rate=0.1,
    reg_lambda=0.1
)

In [ ]:
xgb_clf.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [02:21:38] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "max_features" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_features=4, max_leaves=None, min_child_weight=None,
              missing=nan, monotone_constraints=None, multi_strategy=None,
              n_estimators=6, n_jobs=None, ...)

In [ ]:
y_pred = xgb_clf.predict(x_train)
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1202
           1       1.00      1.00      1.00       841
           2       1.00      1.00      1.00       978
           3       1.00      0.92      0.96       103
           4       1.00      0.87      0.93        76

    accuracy                           0.99      3200
   macro avg       1.00      0.96      0.98      3200
weighted avg       0.99      0.99      0.99      3200