In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('C:\\Users\\Venugopal\\OneDrive\\Desktop\\Batch_423\\EDA\\data\\Iris.csv')

In [5]:
df2=pd.read_csv('C:/Users/Venugopal/OneDrive/Desktop/Batch_423/EDA/data/Iris.csv')

In [9]:
df3=pd.read_csv(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\Iris.csv')

In [10]:
df3

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [11]:
df_xl=pd.read_excel(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\weather_data.xlsx')

In [12]:
df_xl

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [13]:
df=pd.read_csv(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\std_data1.csv')

In [14]:
df

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [15]:
df1=pd.read_csv(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\std_data1.csv',usecols=['ENGLISH'])

In [16]:
df1

   ENGLISH
0       67
1       87
2       66
3       56
4       89
5       88
6       90
7       79

In [17]:
df2=pd.read_csv(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\std_data1.csv',usecols=['SNAME','ENGLISH'])

In [19]:
df2

  SNAME  ENGLISH
0     A       67
1     B       87
2     C       66
3     D       56
4     E       89
5     F       88
6     G       90
7     H       79

In [20]:
df=pd.read_csv(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\std_data1.csv',nrows=5)

In [21]:
df

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56

In [22]:
df=pd.read_csv(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\std_data1.csv',nrows=5,usecols=['SNAME','ENGLISH'])

In [23]:
df

  SNAME  ENGLISH
0     A       67
1     B       87
2     C       66
3     D       56
4     E       89

In [24]:
df=pd.read_csv(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\std_data2.csv')

In [25]:
df

  ABC SCHOOL Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0      SNAME    SCLASS     ENGLISH   COMPUTER    SCIENCE
1          A         10         67         66         66
2          B         12         87         56         65
3          C         11         66         89         63
4          D         10         56         88         66
5          E         10         89         90         56
6          F          9         88         85         89
7          G         12         90         83         88
8          H         11         79         88         90

In [39]:
df=pd.read_csv(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\std_data2.csv',skiprows=1)

In [27]:
df

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [28]:
df=pd.read_csv(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\std_data2.csv',skiprows=2)
df

   A  10  67  66  66.1
0  B  12  87  56    65
1  C  11  66  89    63
2  D  10  56  88    66
3  E  10  89  90    56
4  F   9  88  85    89
5  G  12  90  83    88
6  H  11  79  88    90

In [29]:
df=pd.read_csv(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\std_data1.csv',skiprows=[2])

In [30]:
df

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [36]:
df=pd.read_csv(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\std_data1.csv',skiprows=[3,5,8])
df

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     D       10       56        88       66
3     F        9       88        85       89
4     G       12       90        83       88

In [37]:
df=pd.read_csv(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\std_data1.csv',skiprows=[i for i in range(4,8) ])

In [38]:
df

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     H       11       79        88       90

In [40]:
df

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [41]:
df.iloc[0:3]

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63

In [42]:
df.iloc[:,0:3]

  SNAME  SCLASS   ENGLISH
0     A       10       67
1     B       12       87
2     C       11       66
3     D       10       56
4     E       10       89
5     F        9       88
6     G       12       90
7     H       11       79

In [44]:
df.iloc[4:,3:]

   COMPUTER  SCIENCE
4        90       56
5        85       89
6        83       88
7        88       90

In [46]:
df.loc[4:,'ENGLISH':'SCIENCE']

   ENGLISH  COMPUTER  SCIENCE
4       89        90       56
5       88        85       89
6       90        83       88
7       79        88       90

In [47]:
df

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [48]:
df.loc[:,['SNAME','COMPUTER','SCIENCE']]

  SNAME  COMPUTER  SCIENCE
0     A        66       66
1     B        56       65
2     C        89       63
3     D        88       66
4     E        90       56
5     F        85       89
6     G        83       88
7     H        88       90

In [50]:
df.iloc[:,[0,3,4]]

  SNAME  COMPUTER  SCIENCE
0     A        66       66
1     B        56       65
2     C        89       63
3     D        88       66
4     E        90       56
5     F        85       89
6     G        83       88
7     H        88       90

In [51]:
df.head(3)

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63

In [52]:
df.tail(3)

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [53]:
df.head()

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56

In [54]:
df.tail()

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [55]:
df.columns

Index(['SNAME', 'SCLASS ', 'ENGLISH', 'COMPUTER', 'SCIENCE'], dtype='object')

In [56]:
df

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [59]:
df.to_excel(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\test_excel.xlsx',index=False)

In [60]:
df.to_csv(r'C:\Users\Venugopal\OneDrive\Desktop\Batch_423\EDA\data\test_csv.csv',index=False)