### Pandas DataFrame
A Pandas DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns). It can be thought of as a collection of Series objects that share the same index

### Features of Pandas DataFrame
- Two-Dimensional : Contains rows and columns
- Heterogenous Data : Each column can contain different types of data
- Labeled Axes : Both rows and columns are labeled
- Flexible Data Manipulation : Supports filtering, grouping and transforming data
- Data Integration : Easily integrates with various data sources and formats
- Handling Missing Data : Functions to detect, fill or drop missing values
- Data Aggregation : Methods for grouping, merging and aggregating data

## Dataframe

- Dataframe is the most widely used data-structure in data analysis. 

- `It is a table with rows and columns, with rows having an index and columns having meaningful names.`

**Syntax to create dataframe**

> df = pd.DataFrame(`list,Series,array,dictionary`)

**Creating a DataFrame using list**

In [4]:
import pandas as pd
data = {
    "A" : [1,2,3,4],
    "B" : [3,1,4,1],
    "C" : [12,10,-1,0],
    "D" :[2,3,6,7]
}
df = pd.DataFrame(data)
df

   A  B   C  D
0  1  3  12  2
1  2  1  10  3
2  3  4  -1  6
3  4  1   0  7

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
["r"+str(i) for i in range(len(data["A"]))]

['r0', 'r1', 'r2', 'r3']

In [7]:
import pandas as pd
data = {
    "A" : [1,2,3,4],
    "B" : [3,1,4,1],
    "C" : [12,10,-1,0]
}
df = pd.DataFrame(data, index = ["r"+str(i) for i in range(len(data["A"]))])
# df.columns = ["c"+str(i) for i in range(len(data.keys()))]
df

    A  B   C
r0  1  3  12
r1  2  1  10
r2  3  4  -1
r3  4  1   0

In [8]:
df["sum"] = df.sum(axis=1)
df

    A  B   C  sum
r0  1  3  12   16
r1  2  1  10   13
r2  3  4  -1    6
r3  4  1   0    5

In [9]:
## Create a dataframe with indices as names (atleast 3 rows)
data = {
       "Maths" :[100,100,100],
      "English" : [99, 89, 91],
      "Physics" : [100, 92, 96]
        }
marks = pd.DataFrame(data, index=["Ram", "Sam", "Tom"])

marks

     Maths  English  Physics
Ram    100       99      100
Sam    100       89       92
Tom    100       91       96

In [10]:
## Create a column total and other column average percentage
marks["Total"] = marks.sum(axis= 1)
marks

     Maths  English  Physics  Total
Ram    100       99      100    299
Sam    100       89       92    281
Tom    100       91       96    287

In [11]:
marks["Average"] = marks["Total"]/3
marks

     Maths  English  Physics  Total    Average
Ram    100       99      100    299  99.666667
Sam    100       89       92    281  93.666667
Tom    100       91       96    287  95.666667

In [12]:
marks.mean(axis=0)

Maths      100.000000
English     93.000000
Physics     96.000000
Total      289.000000
Average     96.333333
dtype: float64

In [14]:
df.columns = list('abcd')
df

    a  b   c   d
r0  1  3  12  16
r1  2  1  10  13
r2  3  4  -1   6
r3  4  1   0   5

In [15]:
data = {
    "A" : [1,2,3,4],
    "B" : [3,1,4,1],
    "C" : [12,10,-1,0]
}
df = pd.DataFrame(data, index = ["r"+str(i) for i in range(len(data["A"]))])
df.columns = ["c"+str(i) for i in range(len(data.keys()))]
df

    c0  c1  c2
r0   1   3  12
r1   2   1  10
r2   3   4  -1
r3   4   1   0

In [17]:
# Creating a dataframe using list
list1 = [45,34,89,12,30]
df_list = pd.DataFrame(list1, columns=["Column 1"])

df_list

   Column 1
0        45
1        34
2        89
3        12
4        30

**Creating a DataFrame using Series**

In [18]:
s1 = pd.Series([34,89,76,23,24])  # Creation of DataFrame using Series  
s1, type(s1)

(0    34
 1    89
 2    76
 3    23
 4    24
 dtype: int64,
 pandas.core.series.Series)

In [19]:
df1 = pd.DataFrame(s1)

In [20]:
df1

    0
0  34
1  89
2  76
3  23
4  24

In [21]:
type(df1)

pandas.core.frame.DataFrame

In [69]:
import pandas as pd

# Sample dictionary where keys are row indices
data = {
    'Row1': ["John", 24, "B.Com"],
    'Row2': ["Nick", 25, "B.E."],
    'Row3': ["Tom", 28, "B.Arch"]
}
# Creating DataFrame with dictionary keys as columns
df = pd.DataFrame.from_dict(data, orient='index', columns=['Name', 'Age', 'Qualification'])

df

      Name  Age Qualification
Row1  John   24         B.Com
Row2  Nick   25          B.E.
Row3   Tom   28        B.Arch

In [70]:
dict = {
    "Name" : ["John", "Nick", "Tom"],
    "Age" : [24, 25, 28],
    "Qualification" : ["B.Com", "B.E." , "B.Arch"]
}

df = pd.DataFrame(dict, index = ["Row1" , "Row2", "Row3"])
df

      Name  Age Qualification
Row1  John   24         B.Com
Row2  Nick   25          B.E.
Row3   Tom   28        B.Arch

In [ ]:
data = {
    "A" : [1,2,3,4],
    "B" : [3,1,4,1],
    "C" : [12,10,-1,0]
}
df = pd.DataFrame(data, index = ["r"+str(i) for i in range(len(data["A"]))])
df

In [ ]:
### Create a similar DataFrame as above with dictionary keys as columns names 
### Row_indices should be assigned using "index" parameter of DataFrame

**Creating a DataFrame using Dictionaries**

In [22]:
dict_1 = {
    "Name" : ["A","B","C","D"],
    "Designation":["PM","Dev","TM","Tester"],
    "Location":["Delhi", "Hyderbad", "Chennai","Vizag"],
    "Salary LPA":[20, 12, 13,9]
}

In [23]:
df2 = pd.DataFrame(dict_1)
df2

  Name Designation  Location  Salary LPA
0    A          PM     Delhi          20
1    B         Dev  Hyderbad          12
2    C          TM   Chennai          13
3    D      Tester     Vizag           9

**Creating indexed dataframe**

In [24]:
df3 = pd.DataFrame(dict_1, index = ["person"+f" {i}" for i in range(1,1+len(dict_1["Name"]))])

In [25]:
df3

         Name Designation  Location  Salary LPA
person 1    A          PM     Delhi          20
person 2    B         Dev  Hyderbad          12
person 3    C          TM   Chennai          13
person 4    D      Tester     Vizag           9

In [26]:
df3.dtypes

Name           object
Designation    object
Location       object
Salary LPA      int64
dtype: object

**Creating a DataFrame with NaN values**

- NaN value------ Null value `syntax for NaN -- np.nan`

In [27]:
import numpy as np
import pandas as pd

In [28]:
dict_1 = {
    "Name" : ["A",np.nan,"C","D"],
    "Designation":["PM",np.nan,"TM","Tester"],
    "Location":["Delhi", "Hyderbad", "Chennai","Vizag"],
    "Salary LPA":[20, 12, 13,9]
}

In [29]:
df4 = pd.DataFrame(dict_1)
df4

  Name Designation  Location  Salary LPA
0    A          PM     Delhi          20
1  NaN         NaN  Hyderbad          12
2    C          TM   Chennai          13
3    D      Tester     Vizag           9

In [30]:
df4.to_csv("df4.csv", index = False)

#### Acessing columns values in DataFrame

In [32]:
df4.columns  # Accessing column names of the dataframe

Index(['Name', 'Designation', 'Location', 'Salary LPA'], dtype='object')

In [83]:
df4["Salary LPA"]

0    20
1    12
2    13
3     9
Name: Salary LPA, dtype: int64

In [39]:
type(df4["Name"])

pandas.core.series.Series

In [40]:
df4[["Name"]],type(df4[["Name"]])

(  Name
 0    A
 1  NaN
 2    C
 3    D,
 pandas.core.frame.DataFrame)

In [93]:
df4["Name"]  # Series

0      A
1    NaN
2      C
3      D
Name: Name, dtype: object

In [41]:
df4[["Name"]] # Data Frame

  Name
0    A
1  NaN
2    C
3    D