# Importing csv & excel file

In [1]:
import pandas as pd

### Load CSV file

- To read CSV using pandas, we will use pd.`read_csv` function, and it’s like this:

**4. header**

In [15]:
pd.read_csv('data/std_data_nocols.csv')

   A  10  67  66  66.1
0  B  12  87  56    65
1  C  11  66  89    63
2  D  10  56  88    66
3  E  10  89  90    56
4  F   9  88  85    89
5  G  12  90  83    88
6  H  11  79  88    90

In [16]:
pd.read_csv('data/std_data_nocols.csv',header=None)   
#column names will be index values when hearder=None

   0   1   2   3     4
0  A  10  67  66  66.1
1  B  12  87  56  65.0
2  C  11  66  89  63.0
3  D  10  56  88  66.0
4  E  10  89  90  56.0
5  F   9  88  85  89.0
6  G  12  90  83  88.0
7  H  11  79  88  90.0

**5. names**

In [17]:
pd.read_csv('data/std_data_nocols.csv',header=None,names=["Name","Cls","Eng","Sci","Comp"]) 
#passing column names

  Name  Cls  Eng  Sci  Comp
0    A   10   67   66  66.1
1    B   12   87   56  65.0
2    C   11   66   89  63.0
3    D   10   56   88  66.0
4    E   10   89   90  56.0
5    F    9   88   85  89.0
6    G   12   90   83  88.0
7    H   11   79   88  90.0

**6. index_col**

In [18]:
pd.read_csv('data/std_data1.csv')

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [19]:
pd.read_csv('data/std_data1.csv',index_col="SNAME")   
#changing index by specified column

       SCLASS   ENGLISH  COMPUTER  SCIENCE
SNAME
A           10       67        66       66
B           12       87        56       65
C           11       66        89       63
D           10       56        88       66
E           10       89        90       56
F            9       88        85       89
G           12       90        83       88
H           11       79        88       90

**7. parse_dates**

In [20]:
df_date=pd.read_csv('data/hyd.csv')
df_date

          Date  Temp
0   21-01-2022  30.0
1   22-01-2022  28.0
2   23-01-2022   NaN
3   24-01-2022  29.0
4   25-01-2022  31.0
5   26-01-2022  32.0
6   27-01-2022  34.0
7   28-01-2022   NaN
8   29-01-2022  36.0
9   30-01-2022  38.0
10  31-01-2022   NaN
11  13-02-2022  25.0
12  14-02-2022   NaN
13  15-02-2022  22.0
14  16-02-2022  21.0
15  17-02-2022   NaN
16  18-02-2022  22.0
17  19-02-2022   NaN
18  20-02-2022  20.0

In [58]:
df_date.dtypes    #the datatype of Data column is object

Date     object
Temp    float64
dtype: object

In [22]:
import warnings
warnings.filterwarnings("ignore")

In [23]:
df_date=pd.read_csv('data/hyd.csv',parse_dates=["Date"])
df_date                   #Changing Date column datatype to datetime

         Date  Temp
0  2022-01-21  30.0
1  2022-01-22  28.0
2  2022-01-23   NaN
3  2022-01-24  29.0
4  2022-01-25  31.0
5  2022-01-26  32.0
6  2022-01-27  34.0
7  2022-01-28   NaN
8  2022-01-29  36.0
9  2022-01-30  38.0
10 2022-01-31   NaN
11 2022-02-13  25.0
12 2022-02-14   NaN
13 2022-02-15  22.0
14 2022-02-16  21.0
15 2022-02-17   NaN
16 2022-02-18  22.0
17 2022-02-19   NaN
18 2022-02-20  20.0

In [70]:
df_date.dtypes

Date    datetime64[ns]
Temp           float64
dtype: object

# Explorting csv and excel file

**Export csv file**
- To write CSV using pandas, we will use `to_csv` function, and it’s like this:

In [71]:
df_date.to_csv("exporting.csv")

**Export excel file**
- To write EXCEL using pandas, we will use `to_excel` function, and it’s like this:

In [72]:
df_date.to_excel("exporting.xlsx")

In [ ]:
0import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

## Duplicates

- Sometimes, you get a messy dataset. For example, you may have to deal with duplicates, which will skew your analaysis.

**Checking for duplicates**

- For checking if you have duplicate records.This checks if the whole row appears elsewhere with the same values in each column.

`df.duplicated()`

In [ ]:
# Creating dataframe using dictionary

dict1 = {'Gender': ["Male", "Female", "Male", "Female","Male"],
        'Married':["Yes", "No","No", "No","Yes"],
       'Loan_Status':["Yes", "No", "No", "No","Yes"]}

df = pd.DataFrame(dict1)
df

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No
2    Male      No          No
3  Female      No          No
4    Male     Yes         Yes

In [ ]:
df.duplicated()   #the output of this is boolean value

0    False
1    False
2    False
3     True
4     True
dtype: bool

- In the above dataframe we have 2 duplicate values

In [ ]:
df.drop_duplicates()   #all duplicated values are droped

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No
2    Male      No          No

**Dropping duplicates from a particular column**

- Sometimes, you may want to drop duplicates just from one column.

In [ ]:
df

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No
2    Male      No          No
3  Female      No          No
4    Male     Yes         Yes

In [ ]:
df.drop_duplicates(["Married"])      #Drops duplicate values in a specified column

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No

`first`: (default) Drop duplicates except for the first occurrence.   
`last`: Drop duplicates except for the last occurrence.   
`False`: Drop all duplicates.   
       
The two main methods that we will use are
- duplicated()
- drop_duplicates()

The former returns a boolean series and the latter can be used to directly delete duplicate rows from a dataframe. For duplicated() method the inputs are:   
  
- keep   
    - "first": Mark duplicates as True except for the first occurrence.   
    - "last": Mark duplicates as True except for the last occurrence.   
    - False: Mark all duplicates as True   
      
For the drop_duplicates() method the keep arguments does the following.   
  
- keep  
    - "first": Drop duplicates except for the first occurrence.  
    - "last": Drop duplicates except for the last occurrence.  
    - False: Drop all duplicates
      
The second arguments for both is:   

- `subset`: Only consider certain columns for identifying duplicates. If subset is not specific,  by default all of the columns will be used.

In [ ]:
# with keep = "first" - mark duplicates as True except for the first one

duplicates_first=df.duplicated(keep = "first")
duplicates_first

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [ ]:
df.loc[duplicates_first,:]

   Gender Married Loan_Status
3  Female      No          No
4    Male     Yes         Yes

In [ ]:
# with keep = "last" - mark duplicates as True except for the last one
duplicates_last=df.duplicated(keep = "last")
duplicates_last

0     True
1     True
2    False
3    False
4    False
dtype: bool

In [ ]:
df

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No
2    Male      No          No
3  Female      No          No
4    Male     Yes         Yes

**drop_duplicates**

In [ ]:
df.drop_duplicates(keep = False)

  Gender Married Loan_Status
2   Male      No          No

In [ ]:
# with keep = "first" - keep duplicates which occured first time and drop others

df1 = df.drop_duplicates(keep = "first")
df1

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No
2    Male      No          No

In [ ]:
# with keep = "last" - keep duplicates which occured last time and drop others

df1 = df.drop_duplicates(keep = "last")
df1

   Gender Married Loan_Status
2    Male      No          No
3  Female      No          No
4    Male     Yes         Yes

In [ ]:
#Using drop_duplicates() method with subset

df.drop_duplicates(keep = "first", subset=["Gender"])

   Gender Married Loan_Status
0    Male     Yes         Yes
1  Female      No          No

# Data Types in Pandas

- Data Types is one of the first things we should look at after loading the data.
- pandas never detect the correct data type for all the columns of the imported dataset.
- we should check data types and ensure these are of correct types otherwise we may get unexpected results or errors. 
- Pandas offer a range of methods to easily convert the column data types.

**Data types in pandas**
- `object(str)`-Text or mixed numeric and non-numeric
- `int64`- Integer numbers
- `float`- Floating point numbers
- `bool`- True/False values
- `datetime64,datetime,datetime.timedelta`- datetimeDate and time values

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

### To check the data types of the columns in your DataFrame, pandas has some methods.

- **df.dtypes- Returns a series with the datatypes of each column in the dataframe.**

In [3]:


data = {"Car": ["BMW", "ALTO", "AUDI","MARUTI", "HONDA", "HYUNDAI", "FORD", "KIA"],\
     "Color": ["Red", "Yellow", "Black", "Green", "Black", "Red", "Black", "Black"],\
     "Year": ["1990", "1980", "2003", "2000", "2001", "2004", "1999", "2020"],\
     "Rating": ["2.5", "1.5", "3.8", "9.7", "8.9", "3.2", "5.5", "6.9"],\
     "Service": ["30/04/2023", "31/08/1999", "28/12/2015", "29/06/2011",\
                 "30/12/2020", "31/07/2013", "28/11/2000", "25/12/2020"]}
df = pd.DataFrame(data)
df.head()

      Car   Color  Year Rating     Service
0     BMW     Red  1990    2.5  30/04/2023
1    ALTO  Yellow  1980    1.5  31/08/1999
2    AUDI   Black  2003    3.8  28/12/2015
3  MARUTI   Green  2000    9.7  29/06/2011
4   HONDA   Black  2001    8.9  30/12/2020

In [4]:
df.dtypes    #here we got all columns data types

Car        object
Color      object
Year       object
Rating     object
Service    object
dtype: object

- In the above DataFrame we have 5 columns(Car,Color,Year,Rating,Service)
- lets change the datatype of those columns to correct types

**Correct data types of these columns would be**
- Car    -    object
- Color  -    object
- Year   -    int
- Rating  -   float
- Service   - datetime

### To change the data types of columns, Pandas offer a range of methods to easily convert the column data types.

**df.col_name.astype() - Converting datatype of a particular column.**

In [5]:
df["Year"].astype("int")

0    1990
1    1980
2    2003
3    2000
4    2001
5    2004
6    1999
7    2020
Name: Year, dtype: int32

In [9]:
 df["Year"]= df["Year"].astype("int")

In [10]:
df.dtypes

Car        object
Color      object
Year        int32
Rating     object
Service    object
dtype: object

In [12]:
df["Rating"]= df["Rating"].astype("float")

In [14]:
df.dtypes

Car         object
Color       object
Year         int32
Rating     float64
Service     object
dtype: object

**pd.to_numeric()**- This method is used to convert the data type of the column to the numerical one. As a result, the float64 or int64 will be returned as the new data type of the column based on the values in the column.

In [15]:
data = {"Car": ["BMW", "ALTO", "AUDI","MARUTI", "HONDA", "HYUNDAI", "FORD", "KIA"],\
     "Color": ["Red", "Yellow", "Black", "Green", "Black", "Red", "Black", "Black"],\
     "Year": ["1990", "1980", "2003", "2000", "2001", "2004", "1999", "2020"],\
     "Rating": ["2.5", "1.5", "3.8", "9.7", "8.9", "3.2", "5.5", "6.9"],\
     "Service": ["30/04/2023", "31/08/1999", "28/12/2015", "29/06/2011",\
                 "30/12/2020", "31/07/2013", "28/11/2000", "25/12/2020"]}
df1= pd.DataFrame(data)
df1.head()

      Car   Color  Year Rating     Service
0     BMW     Red  1990    2.5  30/04/2023
1    ALTO  Yellow  1980    1.5  31/08/1999
2    AUDI   Black  2003    3.8  28/12/2015
3  MARUTI   Green  2000    9.7  29/06/2011
4   HONDA   Black  2001    8.9  30/12/2020

In [17]:
df1.dtypes

Car        object
Color      object
Year       object
Rating     object
Service    object
dtype: object

In [18]:
df1["Year"]=pd.to_numeric(df1["Year"])   #Based on the values in the column it coverted into "int"

In [20]:
df1["Rating"]=pd.to_numeric(df1["Rating"])   #Based on the values in the column it coverted into "float"

In [21]:
df1.dtypes

Car         object
Color       object
Year         int64
Rating     float64
Service     object
dtype: object

**pd.to_datetime()**- Here the column gets converted to the DateTime data type. This method accepts 10 optional arguments to help you to decide how to parse the dates.

In [27]:
pd.to_datetime(df1["Service"])

0   2023-04-30
1   1999-08-31
2   2015-12-28
3   2011-06-29
4   2020-12-30
5   2013-07-31
6   2000-11-28
7   2020-12-25
Name: Service, dtype: datetime64[ns]

**Changing multiple columns data types at once**- ust pass the dictionary of column name & data type pairs to **df.col_name.astype()** method

In [28]:
data = {"Car": ["BMW", "ALTO", "AUDI","MARUTI", "HONDA", "HYUNDAI", "FORD", "KIA"],\
     "Color": ["Red", "Yellow", "Black", "Green", "Black", "Red", "Black", "Black"],\
     "Year": ["1990", "1980", "2003", "2000", "2001", "2004", "1999", "2020"],\
     "Rating": ["2.5", "1.5", "3.8", "9.7", "8.9", "3.2", "5.5", "6.9"],\
     "Service": ["30/04/2023", "31/08/1999", "28/12/2015", "29/06/2011",\
                 "30/12/2020", "31/07/2013", "28/11/2000", "25/12/2020"]}
df2= pd.DataFrame(data)
df2.head()

      Car   Color  Year Rating     Service
0     BMW     Red  1990    2.5  30/04/2023
1    ALTO  Yellow  1980    1.5  31/08/1999
2    AUDI   Black  2003    3.8  28/12/2015
3  MARUTI   Green  2000    9.7  29/06/2011
4   HONDA   Black  2001    8.9  30/12/2020

In [29]:
df2.dtypes

Car        object
Color      object
Year       object
Rating     object
Service    object
dtype: object

In [34]:
df2["Service"].astype("datetime64")

0   2023-04-30
1   1999-08-31
2   2015-12-28
3   2011-06-29
4   2020-12-30
5   2013-07-31
6   2000-11-28
7   2020-12-25
Name: Service, dtype: datetime64[ns]

In [36]:
df2=df2.astype({"Year":"int","Rating":"float","Service":"datetime64"})

In [37]:
df2.dtypes

Car                object
Color              object
Year                int32
Rating            float64
Service    datetime64[ns]
dtype: object