In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r'C:\Users\50094875\Documents\Python Core_With Code_Share (1)\Pandas\Pandas\data\Iris.csv')

In [3]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [5]:
df.describe(include='object')

            Species
count           150
unique            3
top     Iris-setosa
freq             50

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.index

RangeIndex(start=0, stop=150, step=1)

In [9]:
df.shape

(150, 6)

In [10]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [11]:
df.isna().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [12]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [15]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [16]:
df[['SepalLengthCm','PetalLengthCm']].sum()

SepalLengthCm    876.5
PetalLengthCm    563.8
dtype: float64

In [18]:
df[['SepalLengthCm','PetalLengthCm']]

     SepalLengthCm  PetalLengthCm
0              5.1            1.4
1              4.9            1.4
2              4.7            1.3
3              4.6            1.5
4              5.0            1.4
..             ...            ...
145            6.7            5.2
146            6.3            5.0
147            6.5            5.2
148            6.2            5.4
149            5.9            5.1

[150 rows x 2 columns]

In [17]:
df[['SepalLengthCm','PetalLengthCm']].sum(axis=1)

0       6.5
1       6.3
2       6.0
3       6.1
4       6.4
       ...
145    11.9
146    11.3
147    11.7
148    11.6
149    11.0
Length: 150, dtype: float64

In [19]:
df['sum_length']=df[['SepalLengthCm','PetalLengthCm']].sum(axis=1)

In [20]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length
0,1,5.1,3.5,1.4,0.2,Iris-setosa,6.5
1,2,4.9,3.0,1.4,0.2,Iris-setosa,6.3
2,3,4.7,3.2,1.3,0.2,Iris-setosa,6.0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,6.1
4,5,5.0,3.6,1.4,0.2,Iris-setosa,6.4
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,11.9
146,147,6.3,2.5,5.0,1.9,Iris-virginica,11.3
147,148,6.5,3.0,5.2,2.0,Iris-virginica,11.7
148,149,6.2,3.4,5.4,2.3,Iris-virginica,11.6
149,150,5.9,3.0,5.1,1.8,Iris-virginica,11.0

In [21]:
df['avg_width']=df[['SepalWidthCm','PetalWidthCm']].mean(axis=1)

In [22]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length,avg_width
0,1,5.1,3.5,1.4,0.2,Iris-setosa,6.5,1.85
1,2,4.9,3.0,1.4,0.2,Iris-setosa,6.3,1.60
2,3,4.7,3.2,1.3,0.2,Iris-setosa,6.0,1.70
3,4,4.6,3.1,1.5,0.2,Iris-setosa,6.1,1.65
4,5,5.0,3.6,1.4,0.2,Iris-setosa,6.4,1.90
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,11.9,2.65
146,147,6.3,2.5,5.0,1.9,Iris-virginica,11.3,2.20
147,148,6.5,3.0,5.2,2.0,Iris-virginica,11.7,2.50
148,149,6.2,3.4,5.4,2.3,Iris-virginica,11.6,2.85
149,150,5.9,3.0,5.1,1.8,Iris-virginica,11.0,2.40

In [24]:
df[['SepalLengthCm','SepalWidthCm','PetalLengthCm']].std()

SepalLengthCm    0.828066
SepalWidthCm     0.433594
PetalLengthCm    1.764420
dtype: float64

In [25]:
df[['SepalLengthCm','SepalWidthCm','PetalLengthCm']].mean()

SepalLengthCm    5.843333
SepalWidthCm     3.054000
PetalLengthCm    3.758667
dtype: float64

In [26]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length,avg_width
0,1,5.1,3.5,1.4,0.2,Iris-setosa,6.5,1.85
1,2,4.9,3.0,1.4,0.2,Iris-setosa,6.3,1.60
2,3,4.7,3.2,1.3,0.2,Iris-setosa,6.0,1.70
3,4,4.6,3.1,1.5,0.2,Iris-setosa,6.1,1.65
4,5,5.0,3.6,1.4,0.2,Iris-setosa,6.4,1.90
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,11.9,2.65
146,147,6.3,2.5,5.0,1.9,Iris-virginica,11.3,2.20
147,148,6.5,3.0,5.2,2.0,Iris-virginica,11.7,2.50
148,149,6.2,3.4,5.4,2.3,Iris-virginica,11.6,2.85
149,150,5.9,3.0,5.1,1.8,Iris-virginica,11.0,2.40

In [27]:
df[df['SepalWidthCm']==df['SepalWidthCm'].max()]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length,avg_width
15,16,5.7,4.4,1.5,0.4,Iris-setosa,7.2,2.4

In [28]:
df['SepalWidthCm'].max()

4.4

In [29]:
df['SepalWidthCm']

0      3.5
1      3.0
2      3.2
3      3.1
4      3.6
      ...
145    3.0
146    2.5
147    3.0
148    3.4
149    3.0
Name: SepalWidthCm, Length: 150, dtype: float64

In [30]:
df['SepalWidthCm']==df['SepalWidthCm'].max()

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Name: SepalWidthCm, Length: 150, dtype: bool

In [32]:
df2=df[df['Species']=='Iris-virginica']

In [33]:
df2

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length,avg_width
100,101,6.3,3.3,6.0,2.5,Iris-virginica,12.3,2.90
101,102,5.8,2.7,5.1,1.9,Iris-virginica,10.9,2.30
102,103,7.1,3.0,5.9,2.1,Iris-virginica,13.0,2.55
103,104,6.3,2.9,5.6,1.8,Iris-virginica,11.9,2.35
104,105,6.5,3.0,5.8,2.2,Iris-virginica,12.3,2.60
105,106,7.6,3.0,6.6,2.1,Iris-virginica,14.2,2.55
106,107,4.9,2.5,4.5,1.7,Iris-virginica,9.4,2.10
107,108,7.3,2.9,6.3,1.8,Iris-virginica,13.6,2.35
108,109,6.7,2.5,5.8,1.8,Iris-virginica,12.5,2.15
109,110,7.2,3.6,6.1,2.5,Iris-virginica,13.3,3.05
110,111,6.5,3.2,5.1,2.0,Iris-virginica,11.6,2.60
111,112,6.4,2.7,5.3,1.9,Iris-virginica,11.7,2.30
112,113,6.8,3.0,5.5,2.1,Iris-virginica,12.3,2.55
113,114,5.7,2.5,5.0,2.0,Iris-virginica,10.7,2.25
114,115,5.8,2.8,5.1,2.4,Iris-virginica,10.9,2.60
115,116,6.4,3.2,5.3,2.3,Iris-virginica,11.7,2.75
116,117,6.5,3.0,5.5,1.8,Iris-virginica,12.0,2.40
117,118,7.7,3.8,6.7,2.2,Iris-virginica,14.4,3.00
118,119,7.7,2.6,6.9,2.3,Iris-virginica,14.6,2.45
119,120,6.0,2.2,5.0,1.5,Iris-virginica,11.0,1.85
120,121,6.9,3.2,5.7,2.3,Iris-virginica,12.6,2.75
121,122,5.6,2.8,4.9,2.0,Iris-virginica,10.5,2.40
122,123,7.7,2.8,6.7,2.0,Iris-virginica,14.4,2.40
123,124,6.3,2.7,4.9,1.8,Iris-virginica,11.2,2.25
124,125,6.7,3.3,5.7,2.1,Iris-virginica,12.4,2.70
125,126,7.2,3.2,6.0,1.8,Iris-virginica,13.2,2.50
126,127,6.2,2.8,4.8,1.8,Iris-virginica,11.0,2.30
127,128,6.1,3.0,4.9,1.8,Iris-virginica,11.0,2.40
128,129,6.4,2.8,5.6,2.1,Iris-virginica,12.0,2.45
129,130,7.2,3.0,5.8,1.6,Iris-virginica,13.0,2.30
130,131,7.4,2.8,6.1,1.9,Iris-virginica,13.5,2.35
131,132,7.9,3.8,6.4,2.0,Iris-virginica,14.3,2.90
132,133,6.4,2.8,5.6,2.2,Iris-virginica,12.0,2.50
133,134,6.3,2.8,5.1,1.5,Iris-virginica,11.4,2.15
134,135,6.1,2.6,5.6,1.4,Iris-virginica,11.7,2.00
135,136,7.7,3.0,6.1,2.3,Iris-virginica,13.8,2.65
136,137,6.3,3.4,5.6,2.4,Iris-virginica,11.9,2.90
137,138,6.4,3.1,5.5,1.8,Iris-virginica,11.9,2.45
138,139,6.0,3.0,4.8,1.8,Iris-virginica,10.8,2.40
139,140,6.9,3.1,5.4,2.1,Iris-virginica,12.3,2.60
140,141,6.7,3.1,5.6,2.4,Iris-virginica,12.3,2.75
141,142,6.9,3.1,5.1,2.3,Iris-virginica,12.0,2.70
142,143,5.8,2.7,5.1,1.9,Iris-virginica,10.9,2.30
143,144,6.8,3.2,5.9,2.3,Iris-virginica,12.7,2.75
144,145,6.7,3.3,5.7,2.5,Iris-virginica,12.4,2.90
145,146,6.7,3.0,5.2,2.3,Iris-virginica,11.9,2.65
146,147,6.3,2.5,5.0,1.9,Iris-virginica,11.3,2.20
147,148,6.5,3.0,5.2,2.0,Iris-virginica,11.7,2.50
148,149,6.2,3.4,5.4,2.3,Iris-virginica,11.6,2.85
149,150,5.9,3.0,5.1,1.8,Iris-virginica,11.0,2.40

In [34]:
df.Species

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [37]:
df[['Species','PetalLengthCm']]

            Species  PetalLengthCm
0       Iris-setosa            1.4
1       Iris-setosa            1.4
2       Iris-setosa            1.3
3       Iris-setosa            1.5
4       Iris-setosa            1.4
..              ...            ...
145  Iris-virginica            5.2
146  Iris-virginica            5.0
147  Iris-virginica            5.2
148  Iris-virginica            5.4
149  Iris-virginica            5.1

[150 rows x 2 columns]

In [38]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length,avg_width
0,1,5.1,3.5,1.4,0.2,Iris-setosa,6.5,1.85
1,2,4.9,3.0,1.4,0.2,Iris-setosa,6.3,1.60
2,3,4.7,3.2,1.3,0.2,Iris-setosa,6.0,1.70
3,4,4.6,3.1,1.5,0.2,Iris-setosa,6.1,1.65
4,5,5.0,3.6,1.4,0.2,Iris-setosa,6.4,1.90
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,11.9,2.65
146,147,6.3,2.5,5.0,1.9,Iris-virginica,11.3,2.20
147,148,6.5,3.0,5.2,2.0,Iris-virginica,11.7,2.50
148,149,6.2,3.4,5.4,2.3,Iris-virginica,11.6,2.85
149,150,5.9,3.0,5.1,1.8,Iris-virginica,11.0,2.40

In [39]:
df.iloc[25:51,:]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length,avg_width
25,26,5.0,3.0,1.6,0.2,Iris-setosa,6.6,1.60
26,27,5.0,3.4,1.6,0.4,Iris-setosa,6.6,1.90
27,28,5.2,3.5,1.5,0.2,Iris-setosa,6.7,1.85
28,29,5.2,3.4,1.4,0.2,Iris-setosa,6.6,1.80
29,30,4.7,3.2,1.6,0.2,Iris-setosa,6.3,1.70
30,31,4.8,3.1,1.6,0.2,Iris-setosa,6.4,1.65
31,32,5.4,3.4,1.5,0.4,Iris-setosa,6.9,1.90
32,33,5.2,4.1,1.5,0.1,Iris-setosa,6.7,2.10
33,34,5.5,4.2,1.4,0.2,Iris-setosa,6.9,2.20
34,35,4.9,3.1,1.5,0.1,Iris-setosa,6.4,1.60
35,36,5.0,3.2,1.2,0.2,Iris-setosa,6.2,1.70
36,37,5.5,3.5,1.3,0.2,Iris-setosa,6.8,1.85
37,38,4.9,3.1,1.5,0.1,Iris-setosa,6.4,1.60
38,39,4.4,3.0,1.3,0.2,Iris-setosa,5.7,1.60
39,40,5.1,3.4,1.5,0.2,Iris-setosa,6.6,1.80
40,41,5.0,3.5,1.3,0.3,Iris-setosa,6.3,1.90
41,42,4.5,2.3,1.3,0.3,Iris-setosa,5.8,1.30
42,43,4.4,3.2,1.3,0.2,Iris-setosa,5.7,1.70
43,44,5.0,3.5,1.6,0.6,Iris-setosa,6.6,2.05
44,45,5.1,3.8,1.9,0.4,Iris-setosa,7.0,2.10
45,46,4.8,3.0,1.4,0.3,Iris-setosa,6.2,1.65
46,47,5.1,3.8,1.6,0.2,Iris-setosa,6.7,2.00
47,48,4.6,3.2,1.4,0.2,Iris-setosa,6.0,1.70
48,49,5.3,3.7,1.5,0.2,Iris-setosa,6.8,1.95
49,50,5.0,3.3,1.4,0.2,Iris-setosa,6.4,1.75
50,51,7.0,3.2,4.7,1.4,Iris-versicolor,11.7,2.30

In [40]:
df.iloc[25:51,[2,4]]

    SepalWidthCm  PetalWidthCm
25           3.0           0.2
26           3.4           0.4
27           3.5           0.2
28           3.4           0.2
29           3.2           0.2
30           3.1           0.2
31           3.4           0.4
32           4.1           0.1
33           4.2           0.2
34           3.1           0.1
35           3.2           0.2
36           3.5           0.2
37           3.1           0.1
38           3.0           0.2
39           3.4           0.2
40           3.5           0.3
41           2.3           0.3
42           3.2           0.2
43           3.5           0.6
44           3.8           0.4
45           3.0           0.3
46           3.8           0.2
47           3.2           0.2
48           3.7           0.2
49           3.3           0.2
50           3.2           1.4

In [41]:
df.loc[25:51,['SepalWidthCm','PetalWidthCm']]

    SepalWidthCm  PetalWidthCm
25           3.0           0.2
26           3.4           0.4
27           3.5           0.2
28           3.4           0.2
29           3.2           0.2
30           3.1           0.2
31           3.4           0.4
32           4.1           0.1
33           4.2           0.2
34           3.1           0.1
35           3.2           0.2
36           3.5           0.2
37           3.1           0.1
38           3.0           0.2
39           3.4           0.2
40           3.5           0.3
41           2.3           0.3
42           3.2           0.2
43           3.5           0.6
44           3.8           0.4
45           3.0           0.3
46           3.8           0.2
47           3.2           0.2
48           3.7           0.2
49           3.3           0.2
50           3.2           1.4
51           3.2           1.5

In [47]:
df.iloc[:,[-1]]

     avg_width
0         1.85
1         1.60
2         1.70
3         1.65
4         1.90
..         ...
145       2.65
146       2.20
147       2.50
148       2.85
149       2.40

[150 rows x 1 columns]

In [48]:
df.loc[df['SepalLengthCm']>5,['Species']]

            Species
0       Iris-setosa
5       Iris-setosa
10      Iris-setosa
14      Iris-setosa
15      Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[118 rows x 1 columns]

In [49]:
df[['SepalLengthCm','Species']]

     SepalLengthCm         Species
0              5.1     Iris-setosa
1              4.9     Iris-setosa
2              4.7     Iris-setosa
3              4.6     Iris-setosa
4              5.0     Iris-setosa
..             ...             ...
145            6.7  Iris-virginica
146            6.3  Iris-virginica
147            6.5  Iris-virginica
148            6.2  Iris-virginica
149            5.9  Iris-virginica

[150 rows x 2 columns]

In [50]:
df[df['SepalLengthCm']>5]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length,avg_width
0,1,5.1,3.5,1.4,0.2,Iris-setosa,6.5,1.85
5,6,5.4,3.9,1.7,0.4,Iris-setosa,7.1,2.15
10,11,5.4,3.7,1.5,0.2,Iris-setosa,6.9,1.95
14,15,5.8,4.0,1.2,0.2,Iris-setosa,7.0,2.10
15,16,5.7,4.4,1.5,0.4,Iris-setosa,7.2,2.40
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,11.9,2.65
146,147,6.3,2.5,5.0,1.9,Iris-virginica,11.3,2.20
147,148,6.5,3.0,5.2,2.0,Iris-virginica,11.7,2.50
148,149,6.2,3.4,5.4,2.3,Iris-virginica,11.6,2.85
149,150,5.9,3.0,5.1,1.8,Iris-virginica,11.0,2.40

In [53]:
df[(df['SepalLengthCm']>5) & (df['PetalLengthCm']>5)]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length,avg_width
83,84,6.0,2.7,5.1,1.6,Iris-versicolor,11.1,2.15
100,101,6.3,3.3,6.0,2.5,Iris-virginica,12.3,2.90
101,102,5.8,2.7,5.1,1.9,Iris-virginica,10.9,2.30
102,103,7.1,3.0,5.9,2.1,Iris-virginica,13.0,2.55
103,104,6.3,2.9,5.6,1.8,Iris-virginica,11.9,2.35
104,105,6.5,3.0,5.8,2.2,Iris-virginica,12.3,2.60
105,106,7.6,3.0,6.6,2.1,Iris-virginica,14.2,2.55
107,108,7.3,2.9,6.3,1.8,Iris-virginica,13.6,2.35
108,109,6.7,2.5,5.8,1.8,Iris-virginica,12.5,2.15
109,110,7.2,3.6,6.1,2.5,Iris-virginica,13.3,3.05
110,111,6.5,3.2,5.1,2.0,Iris-virginica,11.6,2.60
111,112,6.4,2.7,5.3,1.9,Iris-virginica,11.7,2.30
112,113,6.8,3.0,5.5,2.1,Iris-virginica,12.3,2.55
114,115,5.8,2.8,5.1,2.4,Iris-virginica,10.9,2.60
115,116,6.4,3.2,5.3,2.3,Iris-virginica,11.7,2.75
116,117,6.5,3.0,5.5,1.8,Iris-virginica,12.0,2.40
117,118,7.7,3.8,6.7,2.2,Iris-virginica,14.4,3.00
118,119,7.7,2.6,6.9,2.3,Iris-virginica,14.6,2.45
120,121,6.9,3.2,5.7,2.3,Iris-virginica,12.6,2.75
122,123,7.7,2.8,6.7,2.0,Iris-virginica,14.4,2.40
124,125,6.7,3.3,5.7,2.1,Iris-virginica,12.4,2.70
125,126,7.2,3.2,6.0,1.8,Iris-virginica,13.2,2.50
128,129,6.4,2.8,5.6,2.1,Iris-virginica,12.0,2.45
129,130,7.2,3.0,5.8,1.6,Iris-virginica,13.0,2.30
130,131,7.4,2.8,6.1,1.9,Iris-virginica,13.5,2.35
131,132,7.9,3.8,6.4,2.0,Iris-virginica,14.3,2.90
132,133,6.4,2.8,5.6,2.2,Iris-virginica,12.0,2.50
133,134,6.3,2.8,5.1,1.5,Iris-virginica,11.4,2.15
134,135,6.1,2.6,5.6,1.4,Iris-virginica,11.7,2.00
135,136,7.7,3.0,6.1,2.3,Iris-virginica,13.8,2.65
136,137,6.3,3.4,5.6,2.4,Iris-virginica,11.9,2.90
137,138,6.4,3.1,5.5,1.8,Iris-virginica,11.9,2.45
139,140,6.9,3.1,5.4,2.1,Iris-virginica,12.3,2.60
140,141,6.7,3.1,5.6,2.4,Iris-virginica,12.3,2.75
141,142,6.9,3.1,5.1,2.3,Iris-virginica,12.0,2.70
142,143,5.8,2.7,5.1,1.9,Iris-virginica,10.9,2.30
143,144,6.8,3.2,5.9,2.3,Iris-virginica,12.7,2.75
144,145,6.7,3.3,5.7,2.5,Iris-virginica,12.4,2.90
145,146,6.7,3.0,5.2,2.3,Iris-virginica,11.9,2.65
147,148,6.5,3.0,5.2,2.0,Iris-virginica,11.7,2.50
148,149,6.2,3.4,5.4,2.3,Iris-virginica,11.6,2.85
149,150,5.9,3.0,5.1,1.8,Iris-virginica,11.0,2.40

In [54]:
df[(df['SepalLengthCm']>5)&(df['SepalLengthCm']<6)]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length,avg_width
0,1,5.1,3.5,1.4,0.2,Iris-setosa,6.5,1.85
5,6,5.4,3.9,1.7,0.4,Iris-setosa,7.1,2.15
10,11,5.4,3.7,1.5,0.2,Iris-setosa,6.9,1.95
14,15,5.8,4.0,1.2,0.2,Iris-setosa,7.0,2.10
15,16,5.7,4.4,1.5,0.4,Iris-setosa,7.2,2.40
16,17,5.4,3.9,1.3,0.4,Iris-setosa,6.7,2.15
17,18,5.1,3.5,1.4,0.3,Iris-setosa,6.5,1.90
18,19,5.7,3.8,1.7,0.3,Iris-setosa,7.4,2.05
19,20,5.1,3.8,1.5,0.3,Iris-setosa,6.6,2.05
20,21,5.4,3.4,1.7,0.2,Iris-setosa,7.1,1.80
21,22,5.1,3.7,1.5,0.4,Iris-setosa,6.6,2.05
23,24,5.1,3.3,1.7,0.5,Iris-setosa,6.8,1.90
27,28,5.2,3.5,1.5,0.2,Iris-setosa,6.7,1.85
28,29,5.2,3.4,1.4,0.2,Iris-setosa,6.6,1.80
31,32,5.4,3.4,1.5,0.4,Iris-setosa,6.9,1.90
32,33,5.2,4.1,1.5,0.1,Iris-setosa,6.7,2.10
33,34,5.5,4.2,1.4,0.2,Iris-setosa,6.9,2.20
36,37,5.5,3.5,1.3,0.2,Iris-setosa,6.8,1.85
39,40,5.1,3.4,1.5,0.2,Iris-setosa,6.6,1.80
44,45,5.1,3.8,1.9,0.4,Iris-setosa,7.0,2.10
46,47,5.1,3.8,1.6,0.2,Iris-setosa,6.7,2.00
48,49,5.3,3.7,1.5,0.2,Iris-setosa,6.8,1.95
53,54,5.5,2.3,4.0,1.3,Iris-versicolor,9.5,1.80
55,56,5.7,2.8,4.5,1.3,Iris-versicolor,10.2,2.05
59,60,5.2,2.7,3.9,1.4,Iris-versicolor,9.1,2.05
61,62,5.9,3.0,4.2,1.5,Iris-versicolor,10.1,2.25
64,65,5.6,2.9,3.6,1.3,Iris-versicolor,9.2,2.10
66,67,5.6,3.0,4.5,1.5,Iris-versicolor,10.1,2.25
67,68,5.8,2.7,4.1,1.0,Iris-versicolor,9.9,1.85
69,70,5.6,2.5,3.9,1.1,Iris-versicolor,9.5,1.80
70,71,5.9,3.2,4.8,1.8,Iris-versicolor,10.7,2.50
79,80,5.7,2.6,3.5,1.0,Iris-versicolor,9.2,1.80
80,81,5.5,2.4,3.8,1.1,Iris-versicolor,9.3,1.75
81,82,5.5,2.4,3.7,1.0,Iris-versicolor,9.2,1.70
82,83,5.8,2.7,3.9,1.2,Iris-versicolor,9.7,1.95
84,85,5.4,3.0,4.5,1.5,Iris-versicolor,9.9,2.25
88,89,5.6,3.0,4.1,1.3,Iris-versicolor,9.7,2.15
89,90,5.5,2.5,4.0,1.3,Iris-versicolor,9.5,1.90
90,91,5.5,2.6,4.4,1.2,Iris-versicolor,9.9,1.90
92,93,5.8,2.6,4.0,1.2,Iris-versicolor,9.8,1.90
94,95,5.6,2.7,4.2,1.3,Iris-versicolor,9.8,2.00
95,96,5.7,3.0,4.2,1.2,Iris-versicolor,9.9,2.10
96,97,5.7,2.9,4.2,1.3,Iris-versicolor,9.9,2.10
98,99,5.1,2.5,3.0,1.1,Iris-versicolor,8.1,1.80
99,100,5.7,2.8,4.1,1.3,Iris-versicolor,9.8,2.05
101,102,5.8,2.7,5.1,1.9,Iris-virginica,10.9,2.30
113,114,5.7,2.5,5.0,2.0,Iris-virginica,10.7,2.25
114,115,5.8,2.8,5.1,2.4,Iris-virginica,10.9,2.60
121,122,5.6,2.8,4.9,2.0,Iris-virginica,10.5,2.40
142,143,5.8,2.7,5.1,1.9,Iris-virginica,10.9,2.30
149,150,5.9,3.0,5.1,1.8,Iris-virginica,11.0,2.40

In [55]:
df[df['SepalLengthCm'].between(5,6)]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length,avg_width
0,1,5.1,3.5,1.4,0.2,Iris-setosa,6.5,1.85
4,5,5.0,3.6,1.4,0.2,Iris-setosa,6.4,1.90
5,6,5.4,3.9,1.7,0.4,Iris-setosa,7.1,2.15
7,8,5.0,3.4,1.5,0.2,Iris-setosa,6.5,1.80
10,11,5.4,3.7,1.5,0.2,Iris-setosa,6.9,1.95
...,...,...,...,...,...,...,...,...
119,120,6.0,2.2,5.0,1.5,Iris-virginica,11.0,1.85
121,122,5.6,2.8,4.9,2.0,Iris-virginica,10.5,2.40
138,139,6.0,3.0,4.8,1.8,Iris-virginica,10.8,2.40
142,143,5.8,2.7,5.1,1.9,Iris-virginica,10.9,2.30
149,150,5.9,3.0,5.1,1.8,Iris-virginica,11.0,2.40

In [58]:
df[(df['SepalLengthCm']>5)|(df['PetalLengthCm']>5)]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length,avg_width
0,1,5.1,3.5,1.4,0.2,Iris-setosa,6.5,1.85
5,6,5.4,3.9,1.7,0.4,Iris-setosa,7.1,2.15
10,11,5.4,3.7,1.5,0.2,Iris-setosa,6.9,1.95
14,15,5.8,4.0,1.2,0.2,Iris-setosa,7.0,2.10
15,16,5.7,4.4,1.5,0.4,Iris-setosa,7.2,2.40
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,11.9,2.65
146,147,6.3,2.5,5.0,1.9,Iris-virginica,11.3,2.20
147,148,6.5,3.0,5.2,2.0,Iris-virginica,11.7,2.50
148,149,6.2,3.4,5.4,2.3,Iris-virginica,11.6,2.85
149,150,5.9,3.0,5.1,1.8,Iris-virginica,11.0,2.40

In [59]:
df['SepalWidthCm'].idxmax()

15

In [63]:
df.iloc[[df['SepalWidthCm'].idxmax()]]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length,avg_width
15,16,5.7,4.4,1.5,0.4,Iris-setosa,7.2,2.4

In [64]:
df.iloc[[df['SepalWidthCm'].idxmin()]]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,sum_length,avg_width
60,61,5.0,2.0,3.5,1.0,Iris-versicolor,8.5,1.5

In [66]:
df[df['SepalLengthCm'].between(5,6)][['Species','PetalWidthCm']]

            Species  PetalWidthCm
0       Iris-setosa           0.2
4       Iris-setosa           0.2
5       Iris-setosa           0.4
7       Iris-setosa           0.2
10      Iris-setosa           0.2
..              ...           ...
119  Iris-virginica           1.5
121  Iris-virginica           2.0
138  Iris-virginica           1.8
142  Iris-virginica           1.9
149  Iris-virginica           1.8

[67 rows x 2 columns]