## Sorting dataframe
- Sorting dataframe by index
- Sorting dataframe by values

#### Sorting by index

**sort_index is used to sort the DF by index**

By default, the index sorting will be ascending

In [17]:
df

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [18]:
df.sort_index()        #sorting index in ascending order

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
0     A       10       67        66       66
1     B       12       87        56       65
2     C       11       66        89       63
3     D       10       56        88       66
4     E       10       89        90       56
5     F        9       88        85       89
6     G       12       90        83       88
7     H       11       79        88       90

In [19]:
df.sort_index(ascending=False)         #sorting index in descending order

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
7     H       11       79        88       90
6     G       12       90        83       88
5     F        9       88        85       89
4     E       10       89        90       56
3     D       10       56        88       66
2     C       11       66        89       63
1     B       12       87        56       65
0     A       10       67        66       66

#### Sorting dataframe by values
**df.sort_values(by="ENGLISH") → It will sort the dataframe by column**

In [21]:
df.sort_values(by=["ENGLISH"],ascending=False)  #ascending order

  SNAME  SCLASS   ENGLISH  COMPUTER  SCIENCE
6     G       12       90        83       88
4     E       10       89        90       56
5     F        9       88        85       89
1     B       12       87        56       65
7     H       11       79        88       90
0     A       10       67        66       66
2     C       11       66        89       63
3     D       10       56        88       66

 # Missing Values

- The quality of the dataset is very important for any data project. `Garbage in, garbage out.`
- It is therefore essential that we put in the extra effort to ensure that our dataset is as complete and free of errors or missing values.
- Pandas, being one of the best data analysis and manipulation libraries, is quite flexible in handling missing values.
- In Pandas missing values are denoted by `NaN` and `None` both.

**Reasons for missing values in data**
  - Data is not being intentionally filled especially if it is an optional field.(Data does not exists)
  - Human error.
  - If it was a survey, participants might quit the survey halfway.
  - Data being corrupted.

## Checking for missing values
**Pandas library offers two functions two detect missing values.**

- isnull()
- notnull()
- isna( )
- notna( )

The below two are similar to above two’s.

`isnull( ) is similar to isna( ) and notnull( ) is similar to notna( )`

- Above functions returns- `boolean values`

In [ ]:
import pandas as pd
import numpy as np

In [23]:
df=pd.read_csv(r"data\std_multinan.csv")

In [ ]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [ ]:
df.isnull()  #Returns boolean value

    Name  English  Science
0  False    False     False
1  False     True     False
2  False     True     False
3  False     True     False
4  False     True     False
5   True    False      True
6  False    False      True
7   True    False      True
8  False    False     False

In [ ]:
df.notnull()   #Returns boolean values

    Name  English  Science
0   True     True      True
1   True    False      True
2   True    False      True
3   True    False      True
4   True    False      True
5  False     True     False
6   True     True     False
7  False     True     False
8   True     True      True

In [ ]:
df.isna()   #Returns boolean values

    Name  English  Science
0  False    False     False
1  False     True     False
2  False     True     False
3  False     True     False
4  False     True     False
5   True    False      True
6  False    False      True
7   True    False      True
8  False    False     False

In [ ]:
df.notna()   #Returns boolean values

    Name  English  Science
0   True     True      True
1   True    False      True
2   True    False      True
3   True    False      True
4   True    False      True
5  False     True     False
6   True     True     False
7  False     True     False
8   True     True      True

In [ ]:
#parameters

**To check dataframe/series contains missing values or not, we can check that by using .values.any( ).**

In [ ]:
df.isnull().values.any()   #Return if any value in dataframe as NaN

True

**To know how many missing values are present in dataframe/series, we can check that by using .sum()**

In [24]:
df.isnull().sum()

Name        2
English     4
Science     3
dtype: int64

# Handling Missing values

There is not an optimal way to handle missing values. But depending on the characteristics of the dataset and the task, we can choose to:
- Drop the missing values(dropna,drop)
- Fill the missing values
- Replace the missing values

**`Drop the missing values` simply means delete those records in which missing values occurred. For that we have dropna( ) function**

In [25]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [26]:
df.dropna()   #drops all the records contains of NaN

  Name  English  Science
0  AAA     50.0      40.0
8  KKK     90.0      90.0

#### parameters in dropna that we can use

- `axis` It can be 0 and 1. 0 for rows and 1 for columns.
- `how` For this you can pass ‘any’ or ‘all’.
- `thresh` It is the minimum number of valid entries or non missing rows which should be present in each row. Its value can be integer.
- `subset` Define in which columns to look for missing values and drop.
- `inplace` It helps you to make changes permanent or temporary. True for permanent changes and False for temporary changes.

In [ ]:
df.dropna()

  Name  English  Science
0  AAA     50.0      40.0
8  KKK     90.0      90.0

In [ ]:
#axis

In [27]:
df.dropna(axis=0)  #here by default it is axis=0(row drop)

  Name  English  Science
0  AAA     50.0      40.0
8  KKK     90.0      90.0

In [28]:
df.dropna(axis=1)   #here when axis=1(column drop)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
#thresh

In [29]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [31]:
df.dropna(axis=0,thresh=2)   #returns non values which has 7 not less than 7(AT LEAST 2 NON NULL VALUES IN A ROW)

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
6  GGG     45.0       NaN
8  KKK     90.0      90.0

In [32]:
df.dropna(axis=1,thresh=6).count()    #returns non values count which has 6 not less than 6

Name        7
Science     6
dtype: int64

**how**

In [33]:
df.dropna(how="any")

  Name  English  Science
0  AAA     50.0      40.0
8  KKK     90.0      90.0

In [34]:
df.dropna(how="any").count()

Name        2
English     2
Science     2
dtype: int64

**subset**

In [ ]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [35]:
df.dropna(subset=["Name","English"])

  Name  English  Science
0  AAA     50.0      40.0
6  GGG     45.0       NaN
8  KKK     90.0      90.0

**inplace**

In [36]:
df.dropna()  #it is not permanent

  Name  English  Science
0  AAA     50.0      40.0
8  KKK     90.0      90.0

In [37]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [ ]:
df.dropna(inplace=True) #it will make it has permanent change

In [ ]:
df

  Name  English  Science
0  AAA     50.0      40.0
8  KKK     90.0      90.0

**drop**

- drop will drop a specified row or column from the dataframe.
- we use drop when there are more missing values in the column.

In [ ]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [39]:
df.drop(0,axis=0)        #drops English column from the dataframe

  Name  English  Science
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [46]:
df.drop(5)      #drops the specified row from the dataframe

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [ ]:
df.columns

Index(['Name', 'English', 'Science '], dtype='object')

**droping multiple columns**

In [38]:
df.drop(['English','Science '],axis=1)       #drops specified columns

  Name
0  AAA
1  BBB
2  CCC
3  DDD
4  EEE
5  NaN
6  GGG
7  NaN
8  KKK

In [40]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [41]:
df.drop(columns=['English','Science '] )    #this columns parameter also do the samething

  Name
0  AAA
1  BBB
2  CCC
3  DDD
4  EEE
5  NaN
6  GGG
7  NaN
8  KKK

### `Filling the missing values` `fillna()` function that can be applied on the DataFrame in order to replace/fill missing values with a user specified value.**

ways To fill NaN values
- user specified value

- forwardfill(ffill) or backwardfill(bfill)

- Numerical column
 - Mean
 - Median

- Categorical column
 - Mode

- interpolate

**User specified value- Replace missing value with 0 To fill in missing values with a numerical value of 0 (i.e. the value of 0 is an arbitrary value and this can be any other value of user choice)**
- df.fillna(0)

In [ ]:
df=pd.read_csv(r"data\std_multinan.csv")

In [ ]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [42]:
df.fillna(0)    #All the NaN values are filled with 0

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      0.0      45.0
2  CCC      0.0      58.0
3  DDD      0.0      90.0
4  EEE      0.0      55.0
5    0     40.0       0.0
6  GGG     45.0       0.0
7    0     58.0       0.0
8  KKK     90.0      90.0

In [43]:
df.fillna(0,axis=1)

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      0.0      45.0
2  CCC      0.0      58.0
3  DDD      0.0      90.0
4  EEE      0.0      55.0
5    0     40.0       0.0
6  GGG     45.0       0.0
7    0     58.0       0.0
8  KKK     90.0      90.0

**bfill is an short form for backward fill. This bfill will backward fill the values in the series/dataframe.**

In [46]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [ ]:
df.dtypes

Name         object
English     float64
Science     float64
dtype: object

In [47]:
df["English"].fillna(df["English"].mean())

0    50.0
1    56.6
2    56.6
3    56.6
4    56.6
5    40.0
6    45.0
7    58.0
8    90.0
Name: English, dtype: float64

In [ ]:
df.columns

Index(['Name', 'English', 'Science '], dtype='object')

In [48]:
df["Science "].fillna(df["Science "].mean())

0    40.0
1    45.0
2    58.0
3    90.0
4    55.0
5    63.0
6    63.0
7    63.0
8    90.0
Name: Science , dtype: float64

**Fill missing value with the median value- let’s say that you want to fill in the missing value with the median value for each column, you can type the following:**

In [ ]:
#median

In [49]:
df["Science "].fillna(df["Science "].median())

0    40.0
1    45.0
2    58.0
3    90.0
4    55.0
5    56.5
6    56.5
7    56.5
8    90.0
Name: Science , dtype: float64

In [50]:
df["English"].fillna(df["English"].median())

0    50.0
1    50.0
2    50.0
3    50.0
4    50.0
5    40.0
6    45.0
7    58.0
8    90.0
Name: English, dtype: float64

**Fill missing value with the mode value- let’s say that you want to fill in the missing value with the mode value for each column, you can type the following:**

In [ ]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB      NaN      45.0
2  CCC      NaN      58.0
3  DDD      NaN      90.0
4  EEE      NaN      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0

In [ ]:
df["English"].fillna(df["English"].mean(),inplace=True)

In [ ]:
df

  Name  English  Science
0  AAA     50.0      40.0
1  BBB     56.6      45.0
2  CCC     56.6      58.0
3  DDD     56.6      90.0
4  EEE     56.6      55.0
5  NaN     40.0       NaN
6  GGG     45.0       NaN
7  NaN     58.0       NaN
8  KKK     90.0      90.0